POST https://biodesk.onrender.com/api/auth/register
content-type: application/json

{
    "ci": "12312",
    "name": "pass",
    "lastName": "word",
    "email": "prueba@test.com",
    "password": "pass",
    "labName": "Caritas",
    "labRif": "DASdsasasd",
    "labDir": "Donde sea",
    "labPhone": ["04129908266"]
}

--------------------------------------------------

POST http://localhost:3000/api/auth/register
content-type: application/json

{
  "ci": "29910820",
  "name": "Joshua",
  "lastName": "Carrera",
  "email": "joshuacarreraramos@gmail.com",
  "password": "securePass123",
  "lab": {
    "name": "Laboratorio Extranjero",
    "rif": "J-12345678-7",
    "dir": "Av. Principal, calle 123, caracas",
    "phoneNums": ["0212-1234567", "0414-7654321"]
  }
}

-------------------------------------------------

GET http://localhost:3000/api/lab/lab_Laboratorio_Central
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMDM4ZjY5YS0wNDNlLTQzN2ItODkzZS0zOTc1M2ZhY2NjYWUiLCJpYXQiOjE3NDgyNDMwOTcsImV4cCI6MTc0ODMyOTQ5N30.fWxN6KeSomzNhrAgosx6hyzvz1B5xW8JimbZ63Eo_tk

-------------------------------------------------

POST http://localhost:3000/api/lab/selected-lab
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMDM4ZjY5YS0wNDNlLTQzN2ItODkzZS0zOTc1M2ZhY2NjYWUiLCJpYXQiOjE3NDgyNDMwOTcsImV4cCI6MTc0ODMyOTQ5N30.fWxN6KeSomzNhrAgosx6hyzvz1B5xW8JimbZ63Eo_tk

{
  "labId": 1
}

-------------------------------------------------

GET http://localhost:3000/api/system/users
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMDM4ZjY5YS0wNDNlLTQzN2ItODkzZS0zOTc1M2ZhY2NjYWUiLCJpYXQiOjE3NDgyNDMwOTcsImV4cCI6MTc0ODMyOTQ5N30.fWxN6KeSomzNhrAgosx6hyzvz1B5xW8JimbZ63Eo_tk
x-lab-id: 1

-------------------------------------------------

POST https://biodesk.onrender.com/api/lab/init
content-type: application/json

{
    "dbName": "Milenia"
}

--------------------------------------------------

POST http://localhost:3000/api/auth/login
content-type: application/json

{
  "email": "joshuacarreraramos@gmail.com",
  "password": "123456789"
}

--------------------------------------------------

POST http://localhost:3000/api/patients
accept: */*
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyYjg0OWQwMi03Y2JjLTQzY2EtODQ3MC0zYTA0NjU1NmRhYzYiLCJpYXQiOjE3NDk5NTcyMTQsImV4cCI6MTc1MDA0MzYxNH0.37aRoVaoWKVxZQdJg-ELmM8idb45n_JswZ1BWlEaeMc
x-lab-id: 16

{
  "ci": "v12345649",
  "name": "john2",
  "lastName": "doe2",
  "secondLastName": "ripper",
  "gender": "MALE",
  "email": "johndoe2@xample.com",
  "dir": "Av. Principal #123",
  "phoneNums": [
    "04121234567",
    "02121234567"
  ],
  "birthDate": "2025-06-14T00:00:00Z"
}

PATCH http://localhost:3000/api/patients/1
accept: */*
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyYjg0OWQwMi03Y2JjLTQzY2EtODQ3MC0zYTA0NjU1NmRhYzYiLCJpYXQiOjE3NDk5NTcyMTQsImV4cCI6MTc1MDA0MzYxNH0.37aRoVaoWKVxZQdJg-ELmM8idb45n_JswZ1BWlEaeMc
x-lab-id: 16

{
  "ci": "v12345678",
  "name": "john2",
  "lastName": "doe2",
  "secondLastName": "ripper",
  "gender": "MALE",
  "email": "johndoe2@xample.com",
  "dir": "Av. Principal #123",
  "phoneNums": [
    "04121234567",
    "02121234567"
  ],
  "birthDate": "2025-06-14T00:00:00Z"
}

GET http://localhost:3000/api/patients/
accept: */*
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyYjg0OWQwMi03Y2JjLTQzY2EtODQ3MC0zYTA0NjU1NmRhYzYiLCJpYXQiOjE3NDk5NTcyMTQsImV4cCI6MTc1MDA0MzYxNH0.37aRoVaoWKVxZQdJg-ELmM8idb45n_JswZ1BWlEaeMc
x-lab-id: 16

GET http://localhost:3000/api/patients/1
accept: */*
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyYjg0OWQwMi03Y2JjLTQzY2EtODQ3MC0zYTA0NjU1NmRhYzYiLCJpYXQiOjE3NDk5NTcyMTQsImV4cCI6MTc1MDA0MzYxNH0.37aRoVaoWKVxZQdJg-ELmM8idb45n_JswZ1BWlEaeMc
x-lab-id: 16
